# Matthew Dorsey
# 2022-07-29

# This script compiles and exectues the ProgramToEcho.java program, which 
# converts files (esp. programs) to scripts that when exectued, echo the 
# entirely of the program to a file

## ARGUMENTS 
# first argument: file name
PROGRAM=$1
# second argument: the executable generated by the program
ECHO=$2

## PARAMETERS
# location of java files
LOC=./simbin/java

## SCRIPT
# compiles the ProgramToEcho java file
javac $LOC/ProgramToEcho.java

# executes the ProgramToEcho program
java -cp $LOC ProgramToEcho $PROGRAM $ECHO
chmod u+x $ECHO
